/**
 * This can be achieved by using the try...catch syntax
 * We use try...catch statements within our async functions for error handling.
 */